# Generated by Django 4.1.2 on 2023-05-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("film_service", "0002_film_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="film",
            name="actors",
            field=models.ManyToManyField(related_name="Films", to="film_service.actor"),
        ),
        migrations.AddField(
            model_name="film",
            name="categories",
            field=models.ManyToManyField(
                related_name="Films", to="film_service.category"
            ),
        ),
        migrations.AddField(
            model_name="film",
            name="genres",
            field=models.ManyToManyField(related_name="Films", to="film_service.genre"),
        ),
    ]
