from django.urls import path

from .views import (
    actor_create,
    actor_delete,
    actor_list,
    actor_update,
    category_create,
    category_delete,
    category_list,
    category_update,
    film_create,
    film_delete,
    film_list,
    film_update,
    genre_create,
    genre_delete,
    genre_list,
    genre_update,
    user_create,
    user_delete,
    user_films_create,
    user_films_delete,
    user_films_list,
    user_films_update,
    user_list,
    user_update,
)

urlpatterns = [
    path("actors/", actor_list, name="actor_list"),
    path("actors/create/", actor_create, name="actor_create"),
    path("actors/<int:pk>/update/", actor_update, name="actor_update"),
    path("actors/<int:pk>/delete/", actor_delete, name="actor_delete"),
    path("categories/", category_list, name="category_list"),
    path("categories/create/", category_create, name="category_create"),
    path("categories/<int:pk>/update/", category_update, name="category_update"),
    path("categories/<int:pk>/delete/", category_delete, name="category_delete"),
    path("films/", film_list, name="film_list"),
    path("films/create/", film_create, name="film_create"),
    path("films/<int:pk>/update/", film_update, name="film_update"),
    path("films/<int:pk>/delete/", film_delete, name="film_delete"),
    path("genres/", genre_list, name="genre_list"),
    path("genres/create/", genre_create, name="genre_create"),
    path("genres/<int:pk>/update/", genre_update, name="genre_update"),
    path("genres/<int:pk>/delete/", genre_delete, name="genre_delete"),
    path("users/", user_list, name="user_list"),
    path("users/create/", user_create, name="user_create"),
    path("users/<int:pk>/update/", user_update, name="user_update"),
    path("users/<int:pk>/delete/", user_delete, name="user_delete"),
    path("user_films/", user_films_list, name="user_films_list"),
    path("user_films/create/", user_films_create, name="user_films_create"),
    path("user_films/<int:pk>/update/", user_films_update, name="user_films_update"),
    path("user_films/<int:pk>/delete/", user_films_delete, name="user_films_delete"),
]